USE [master]
GO

/****** Object:  Database [newssitedb]    Script Date: 2/3/2022 3:08:22 PM ******/
CREATE DATABASE [newssitedb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'newssitedb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\newssitedb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'newssitedb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\newssitedb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [newssitedb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [newssitedb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [newssitedb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [newssitedb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [newssitedb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [newssitedb] SET ARITHABORT OFF 
GO

ALTER DATABASE [newssitedb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [newssitedb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [newssitedb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [newssitedb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [newssitedb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [newssitedb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [newssitedb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [newssitedb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [newssitedb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [newssitedb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [newssitedb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [newssitedb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [newssitedb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [newssitedb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [newssitedb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [newssitedb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [newssitedb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [newssitedb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [newssitedb] SET  MULTI_USER 
GO

ALTER DATABASE [newssitedb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [newssitedb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [newssitedb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [newssitedb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [newssitedb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [newssitedb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [newssitedb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [newssitedb] SET  READ_WRITE 
GO

